### ISSUE TITLE
[Database] PostgreSQL issues

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#320]
I'm trying to run Dirigible against PostgreSQL database, but I hit the following issues:

- [x] **Could not create ACTIVEMQ_MSGS table** - #316
- [x] **ERROR: syntax error at or near "PRIMARY"** - #317
- [x] **Multiple primary keys for table "activemq_acks" are not allowed** - #318
- [x] **~Synchronizing process for Roles and Access artifacts failed~** - #319

~Finally, accessing the home page results into the following exception in the browser (#319):~
```html
HTTP Status 500 - SELECT * FROM DIRIGIBLE_SECURITY_ACCESS
type Exception report

message SELECT * FROM DIRIGIBLE_SECURITY_ACCESS

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.eclipse.dirigible.database.persistence.PersistenceException: SELECT * FROM DIRIGIBLE_SECURITY_ACCESS
	org.eclipse.dirigible.database.persistence.processors.entity.PersistenceQueryProcessor.findAll(PersistenceQueryProcessor.java:255)
	org.eclipse.dirigible.database.persistence.PersistenceManager.findAll(PersistenceManager.java:266)
	org.eclipse.dirigible.core.security.service.SecurityCoreService.getAccessDefinitions(SecurityCoreService.java:385)
	org.eclipse.dirigible.core.security.verifier.AccessVerifier.getMatchingAccessDefinitions(AccessVerifier.java:52)
	org.eclipse.dirigible.runtime.security.filter.SecurityFilter.doFilter(SecurityFilter.java:89)
	org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:474)
	org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:319)
	org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:289)
	org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:201)
	com.google.inject.servlet.DefaultFilterPipeline.dispatch(DefaultFilterPipeline.java:43)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
root cause

org.postgresql.util.PSQLException: ERROR: relation "dirigible_security_access" does not exist
  Position: 15
	org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82)
	org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82)
	org.eclipse.dirigible.database.persistence.processors.entity.PersistenceQueryProcessor.findAll(PersistenceQueryProcessor.java:241)
	org.eclipse.dirigible.database.persistence.PersistenceManager.findAll(PersistenceManager.java:266)
	org.eclipse.dirigible.core.security.service.SecurityCoreService.getAccessDefinitions(SecurityCoreService.java:385)
	org.eclipse.dirigible.core.security.verifier.AccessVerifier.getMatchingAccessDefinitions(AccessVerifier.java:52)
	org.eclipse.dirigible.runtime.security.filter.SecurityFilter.doFilter(SecurityFilter.java:89)
	org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:474)
	org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:319)
	org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:289)
	org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:201)
	com.google.inject.servlet.DefaultFilterPipeline.dispatch(DefaultFilterPipeline.java:43)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
note The full stack trace of the root cause is available in the Apache Tomcat/8.5.8 logs.

Apache Tomcat/8.5.8
```

**Comment by delchev** [comment]
Fixed with the new version of ActiveMQ
